allowBuilds:
  '@gouvfr/dsfr': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - pnpm@11.21.0
  - '@testing-library/jest-dom@7.0.1'
shellEmulator: true
