export {
  GiChocolateBar,
  RiArrowDownLine,
  RiArrowDropDownLine,
  RiArrowDropUpLine,
  RiAddCircleLine,
  RiCloseLine,
  RiFileCopyLine,
  RiMoonLine,
  RiRefreshLine,
  SiDiscord,
  SiGithub,
  SiNpm,
  SiNuxtdotjs,
  SiVisualstudiocode,
  ViFileTypeStorybook,
} from 'oh-vue-icons/icons'
